// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIXProject4
{
    internal sealed partial class Vsix
    {
        public const string Id = "VSIXProject4.bb84b112-6c6d-4312-bbb5-a8b9f38c69c6";
        public const string Name = "VSIXProject4";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Daniel Sandberg";
        public const string Tags = "";
    }
}
