// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIXProject4
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string commandIconString = "4537d792-6e3d-4118-bc58-83177cc105ab";
        public static Guid commandIcon = new Guid(commandIconString);

        public const string VSIXProject4String = "74863b99-dc65-4f66-b21c-9fe4bf1aaa40";
        public static Guid VSIXProject4 = new Guid(VSIXProject4String);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int commandIcon1 = 0x0001;
        public const int AddResourcesCommand = 0x0100;
    }
}