// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ResXHelper
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string testIconString = "cbab31d8-6741-4c6f-9424-29b19e62b234";
        public static Guid testIcon = new Guid(testIconString);

        public const string guidResXHelperPackageString = "7f93a347-7bf3-4fb7-925c-b6237a56cbc2";
        public static Guid guidResXHelperPackage = new Guid(guidResXHelperPackageString);

        public const string guidToolbarButtonPackageCmdSetString = "d77d4996-fc82-48a4-8c0f-ce49bf2e7966";
        public static Guid guidToolbarButtonPackageCmdSet = new Guid(guidToolbarButtonPackageCmdSetString);

        public const string guidImagesString = "16e11665-7c2c-4647-b05f-8e33cced946d";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int testIcon1 = 0x0001;
        public const int AddResourcesCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}