// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ResXHelper_2022
{
    internal sealed partial class Vsix
    {
        public const string Id = "d24db090-0050-4d8b-b722-a91c94b0c4e4";
        public const string Name = "ResX Helper 2022";
        public const string Description = @"Adds a right click menu to the solution explorer where you can specify a base filename and a list of languages.
Once you click Add file(s) the corresponding .resx files will be created.Adds a right click menu to the solution explorer where you can specify a base filename and a list of languages.
Once you click Add file(s) the corresponding .resx files will be created.";
        public const string Language = "en-US";
        public const string Version = "0.1";
        public const string Author = "Daniel Sandberg";
        public const string Tags = "";
    }
}
