//global using Community.VisualStudio.Toolkit;
//global using Microsoft.VisualStudio.Settings;
//global using Microsoft.VisualStudio.Shell;
//global using Microsoft.VisualStudio.Shell.Settings;
//global using ResXHelper2022;
//global using ResXHelper2022.Model;
//global using ResXHelper2022.Options;
//global using System;
//global using System.Collections.Generic;
//global using System.ComponentModel;
//global using System.IO;
//global using System.Linq;
//global using System.Reflection;
//global using System.Runtime.InteropServices;
//global using System.Text.Json;
//global using System.Text.Json.Serialization;
//global using System.Threading;
//global using System.Windows.Forms;
//global using static ResXHelper2022.OptionsProvider;
//global using Task = System.Threading.Tasks.Task;
//global using System.Collections.ObjectModel;
//global using System.Windows;
//global using ListBox = System.Windows.Controls.ListBox;
//global using System.Windows.Controls;
//global using System.Windows.Data;
//global //Code copied from https://github.com/madskristensen/AddAnyFile
//using Microsoft.VisualStudio.PlatformUI;
//global using Control = System.Windows.Controls.Control;
//global //Code copied from https://github.com/madskristensen/AddAnyFile
//using Microsoft;
//global using Microsoft.VisualStudio.Shell.Interop;
//global using Application = System.Windows.Application;
//global using ComboBox = System.Windows.Controls.ComboBox;
//global using TextBox = System.Windows.Controls.TextBox;
//global using UserControl = System.Windows.Forms.UserControl;
