// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ResXHelper2022
{
    internal sealed partial class Vsix
    {
        public const string Id = "27bf0bda-a4e6-431c-a350-f38a7b74bbf6";
        public const string Name = "ResXHelper2022";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Daniel Sandberg";
        public const string Tags = "";
    }
}
