// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ResXHelper2022
{
    internal sealed partial class Vsix
    {
        public const string Id = "7CAF59FC-323F-48E8-8ACD-BB062BD339F4";
        public const string Name = "ResX Helper 2022";
        public const string Description = @"Adds a right click menu to the solution explorer where you can specify a base filename and a list of languages.
Once you click Add file(s) the corresponding .resx files will be created.";
        public const string Language = "en-US";
        public const string Version = "1.1";
        public const string Author = "BDSoftware";
        public const string Tags = "";
    }
}
