// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ResXHelper2022
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string commandIconString = "cc8d4b09-a9ba-4c18-a0d8-526b2929b47a";
        public static Guid commandIcon = new Guid(commandIconString);

        public const string ResXHelper2022String = "3cc60c5a-3658-46ee-80eb-89a2d780cb52";
        public static Guid ResXHelper2022 = new Guid(ResXHelper2022String);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int commandIcon1 = 0x0001;
        public const int AddResourcesCommand = 0x0100;
    }
}